version: '3.8'

services:
  # Next.js 主網站
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oece-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=768
    mem_limit: 1g
    mem_reservation: 512m
    cpus: 0.5
    networks:
      - oece-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Telegram Bot
  telegram-bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: oece-telegram-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    env_file:
      - .env
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.3
    networks:
      - oece-network
    depends_on:
      - web

networks:
  oece-network:
    driver: bridge
